name: 'Update FS'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on:
#   schedule:
#     - cron:  '0 6 * * 0'

# Horrible hack to manually trigger the action.
on:
  watch:
    types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install deps and run updater
    - name: Install dependencies
      run: 'pip install -r requirements.txt'
       
    - name: Run the updater
      run: 'python foolslide_scraper/scraper_replacer.py'
      env: 
        SHEETS_API_KEY: ${{ secrets.SHEETS_API_KEY }}
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.8.0
      with:
        commit-message: 'Actions: Update FS list'
        title: Automatic FS Update
        body: This is an automatic FS update for the extension.
        branch: master
